apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: sinatra-example
  name: ruby-22-centos7
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: centos/ruby-22-centos7
    from:
      kind: DockerImage
      name: centos/ruby-22-centos7
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
status:
  dockerImageRepository: ""
