apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: sinatra-example
  name: sinatra-example
spec:
  replicas: 1
  selector:
    app: sinatra-example
    deploymentconfig: sinatra-example
  strategy:
    resources: {}
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: sinatra-example
        deploymentconfig: sinatra-example
    spec:
      containers:
      - image: sinatra-example:latest
        name: sinatra-example
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - sinatra-example
      from:
        kind: ImageStreamTag
        name: sinatra-example:latest
    type: ImageChange
