apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: sinatra-example
  name: sinatra-example
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: sinatra-example:latest
  postCommit: {}
  resources: {}
  source:
    git:
      uri: https://github.com/openshift-quickstart/sinatra-example.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ruby-22-centos7:latest
    type: Source
  triggers:
  - github:
      secret: mA7GLDf7v_uxATxp8d3j
    type: GitHub
  - generic:
      secret: Qqh5cDZGeVk4X3N-MO9k
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
